### ISSUE TITLE
media queries not working in index

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#637]
It appears that we cannot use media queries with the index page.
The document orientation isn't recognized and we cannot use max-device-width, maybe because the device-width info isn't updated on orientation change?

My index page uses media queries like other pages from my book, but only the index page (fullscreen) has problems with it's resize on orientation change.

Here's an simple test:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>index</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/test.css">
  </head>
  <body>
    <div id="wrapper">
    </div>
  </body>
</html>
```

``` css
body {
    margin: 0;
}

#wrapper {
    width: 100px;
    height: 100px;
    background-color: red;
}

/* Portrait */
@media only screen and (orientation : portrait) {

    #wrapper {
        width: 768px;
        height: 1024px;
        background-color: yellow;
    }

}

/* Landscape */
@media only screen and (orientation : landscape) {

    #wrapper {
        width: 1024px;
        height: 768px;
        background-color: blue;
    }

}
```

![Capture d e cran 2013-01-15 a 16 30 50](https://f.cloud.github.com/assets/1521015/68078/a2475762-5f28-11e2-876c-38c1e3c2c447.png)
![Capture d e cran 2013-01-15 a 16 31 01](https://f.cloud.github.com/assets/1521015/68080/a7f6c2e2-5f28-11e2-8c3b-28729cf31963.png)

And when using device-width instead of orientation in media queries

``` css
body {
    margin: 0;
}

#wrapper {
    width: 100px;
    height: 100px;
    background-color: red;
}

/* Portrait */
@media only screen and (max-device-width : 768px) {

    #wrapper {
        width: 768px;
        height: 1024px;
        background-color: green;
    }

}

/* Landscape */
@media only screen and (max-device-width : 1024px) {

    #wrapper {
        width: 1024px;
        height: 768px;
        background-color: purple;
    }

}
```

![Capture d e cran 2013-01-15 a 16 37 02](https://f.cloud.github.com/assets/1521015/68103/94049844-5f29-11e2-9d80-49b0e822f971.png)
![Capture d e cran 2013-01-15 a 16 37 08](https://f.cloud.github.com/assets/1521015/68104/987fbe62-5f29-11e2-89a9-8d2727de3636.png)
