### ISSUE TITLE
Page-as-PNG: which resolution is enough for Retina?

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#930]
I'm building my magazine as a list of big PNG images,
1 image per page (just "IMG SRC" in the html documents),
almost like discussed here - #802 

There are a lot of text on my PNGs, so it is great to have 
zoom possibility for those readers, who want to have the text a bit bigger.
It's OK.
Now I use 1536x2048px PNGs on my iPad1, 
and I can zoom my pages/images, keeping text sharp.
Great.

But, it seems like my images a bit oversized indeed:
Not-too-fast loading, and I see twitch when zooming.

So the question is - what resolution of so kind text-page-PNGs are enough for Retina displays? 
(when we want to keep possibility to zoom a little bit,
if there will be small sized text)

_I have no Retina-iPad, that's why my question appears_

**Comment by aspek** [comment]
You can use JPEG instead of PNG. And set quality 40-70 % recommend 40-50%. The images size is much smaller. 
So if you set zoom maximum-scale= 1.5; You should bring it to calculate.
1536 x 1.5 = 2304px
2048 x 1.5 = 3072px
The true image size is 2304x3072 px

In your case it is  HTML TAG  `<img src = "???.jpg" style="width:768px; height:1024px;" >` use style to resize it. 

But if it is Background image in CSS you can use something like this

``` css
.boxContentPortrait{
        background-image:url(???.jpg);
        background-repeat:no-repeat;
        width:768px; height:1024px; 
        -webkit-background-size:768px 1024px;
        background-size:768px 1024px;
}
```

This way no need `(-webkit-min-device-pixel-ratio: 2)` .Now you will have just one image TEXT,BG, or what ever  per page. Make your  book smaller and load much faster. Sorry for my English. Hope you can understand me.
